# Generated by Django 2.1.7 on 2019-04-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imageb',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
